// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountByOwnerID = `-- name: GetAccountByOwnerID :one
SELECT id, owner_id, balance, currency, created_at, updated_at FROM accounts
WHERE owner_id = $1
LIMIT 1
`

func (q *Queries) GetAccountByOwnerID(ctx context.Context, ownerID uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByOwnerID, ownerID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrCreateAccount = `-- name: GetOrCreateAccount :one
INSERT INTO accounts (owner_id, balance, currency)
VALUES ($1, 0, 'XLM')
ON CONFLICT (owner_id) DO UPDATE SET updated_at = now()
RETURNING id, owner_id, balance, currency, created_at, updated_at
`

func (q *Queries) GetOrCreateAccount(ctx context.Context, ownerID uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getOrCreateAccount, ownerID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
SET balance = $2, updated_at = now()
WHERE id = $1
RETURNING id, owner_id, balance, currency, created_at, updated_at
`

type UpdateAccountBalanceParams struct {
	ID      uuid.UUID      `json:"id"`
	Balance pgtype.Numeric `json:"balance"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance, arg.ID, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
