// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_endpoints.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO api_endpoints (provider_id, route, method, price_amount, currency, rate_limit, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, provider_id, route, method, price_amount, currency, rate_limit, status, created_at, updated_at
`

type CreateEndpointParams struct {
	ProviderID  uuid.UUID      `json:"provider_id"`
	Route       string         `json:"route"`
	Method      string         `json:"method"`
	PriceAmount pgtype.Numeric `json:"price_amount"`
	Currency    Currency       `json:"currency"`
	RateLimit   pgtype.Int4    `json:"rate_limit"`
	Status      EndpointStatus `json:"status"`
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (ApiEndpoint, error) {
	row := q.db.QueryRow(ctx, createEndpoint,
		arg.ProviderID,
		arg.Route,
		arg.Method,
		arg.PriceAmount,
		arg.Currency,
		arg.RateLimit,
		arg.Status,
	)
	var i ApiEndpoint
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Route,
		&i.Method,
		&i.PriceAmount,
		&i.Currency,
		&i.RateLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEndpoint = `-- name: DeleteEndpoint :one
DELETE FROM api_endpoints
WHERE id = $1
RETURNING id, provider_id, route, method, price_amount, currency, rate_limit, status, created_at, updated_at
`

func (q *Queries) DeleteEndpoint(ctx context.Context, id uuid.UUID) (ApiEndpoint, error) {
	row := q.db.QueryRow(ctx, deleteEndpoint, id)
	var i ApiEndpoint
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Route,
		&i.Method,
		&i.PriceAmount,
		&i.Currency,
		&i.RateLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndpointByID = `-- name: GetEndpointByID :one
SELECT id, provider_id, route, method, price_amount, currency, rate_limit, status, created_at, updated_at
FROM api_endpoints
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetEndpointByID(ctx context.Context, id uuid.UUID) (ApiEndpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointByID, id)
	var i ApiEndpoint
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Route,
		&i.Method,
		&i.PriceAmount,
		&i.Currency,
		&i.RateLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndpointByProviderRouteMethod = `-- name: GetEndpointByProviderRouteMethod :one
SELECT id, provider_id, route, method, price_amount, currency, rate_limit, status, created_at, updated_at
FROM api_endpoints
WHERE provider_id = $1
  AND route = $2
  AND method = $3
LIMIT 1
`

type GetEndpointByProviderRouteMethodParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Route      string    `json:"route"`
	Method     string    `json:"method"`
}

func (q *Queries) GetEndpointByProviderRouteMethod(ctx context.Context, arg GetEndpointByProviderRouteMethodParams) (ApiEndpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointByProviderRouteMethod, arg.ProviderID, arg.Route, arg.Method)
	var i ApiEndpoint
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Route,
		&i.Method,
		&i.PriceAmount,
		&i.Currency,
		&i.RateLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEndpointsByProvider = `-- name: ListEndpointsByProvider :many
SELECT id, provider_id, route, method, price_amount, currency, rate_limit, status, created_at, updated_at
FROM api_endpoints
WHERE provider_id = $1
  AND ($2 IS NULL OR status = $2)
ORDER BY created_at DESC
`

type ListEndpointsByProviderParams struct {
	ProviderID uuid.UUID   `json:"provider_id"`
	Status     interface{} `json:"status"`
}

func (q *Queries) ListEndpointsByProvider(ctx context.Context, arg ListEndpointsByProviderParams) ([]ApiEndpoint, error) {
	rows, err := q.db.Query(ctx, listEndpointsByProvider, arg.ProviderID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiEndpoint
	for rows.Next() {
		var i ApiEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Route,
			&i.Method,
			&i.PriceAmount,
			&i.Currency,
			&i.RateLimit,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEndpoint = `-- name: UpdateEndpoint :one
UPDATE api_endpoints
SET route = $2,
    method = $3,
    price_amount = $4,
    currency = $5,
    rate_limit = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, provider_id, route, method, price_amount, currency, rate_limit, status, created_at, updated_at
`

type UpdateEndpointParams struct {
	ID          uuid.UUID      `json:"id"`
	Route       string         `json:"route"`
	Method      string         `json:"method"`
	PriceAmount pgtype.Numeric `json:"price_amount"`
	Currency    Currency       `json:"currency"`
	RateLimit   pgtype.Int4    `json:"rate_limit"`
}

func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (ApiEndpoint, error) {
	row := q.db.QueryRow(ctx, updateEndpoint,
		arg.ID,
		arg.Route,
		arg.Method,
		arg.PriceAmount,
		arg.Currency,
		arg.RateLimit,
	)
	var i ApiEndpoint
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Route,
		&i.Method,
		&i.PriceAmount,
		&i.Currency,
		&i.RateLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEndpointStatus = `-- name: UpdateEndpointStatus :one
UPDATE api_endpoints
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, provider_id, route, method, price_amount, currency, rate_limit, status, created_at, updated_at
`

type UpdateEndpointStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status EndpointStatus `json:"status"`
}

func (q *Queries) UpdateEndpointStatus(ctx context.Context, arg UpdateEndpointStatusParams) (ApiEndpoint, error) {
	row := q.db.QueryRow(ctx, updateEndpointStatus, arg.ID, arg.Status)
	var i ApiEndpoint
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Route,
		&i.Method,
		&i.PriceAmount,
		&i.Currency,
		&i.RateLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
