// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteKey = `-- name: DeleteKey :one
DELETE FROM api_keys
WHERE id = $1
RETURNING id, user_id, key_hash, label, status, created_at, expires_at
`

func (q *Queries) DeleteKey(ctx context.Context, id uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, deleteKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.Label,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getKeyByHash = `-- name: GetKeyByHash :one
SELECT id, user_id, key_hash, label, status, created_at, expires_at
FROM api_keys
WHERE key_hash = $1
LIMIT 1
`

func (q *Queries) GetKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.Label,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getKeyByID = `-- name: GetKeyByID :one
SELECT id, user_id, key_hash, label, status, created_at, expires_at
FROM api_keys
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetKeyByID(ctx context.Context, id uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.Label,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getKeyWithUserAndAccount = `-- name: GetKeyWithUserAndAccount :one
SELECT
    k.id AS api_key_id,
    k.user_id,
    k.key_hash,
    k.label,
    k.status,
    k.created_at,
    k.expires_at,
    u.email,
    a.id AS account_id,
    a.balance,
    a.currency
FROM api_keys k
JOIN users u ON k.user_id = u.id
JOIN accounts a ON u.id = a.owner_id
WHERE k.key_hash = $1
LIMIT 1
`

type GetKeyWithUserAndAccountRow struct {
	ApiKeyID  uuid.UUID          `json:"api_key_id"`
	UserID    uuid.UUID          `json:"user_id"`
	KeyHash   string             `json:"key_hash"`
	Label     pgtype.Text        `json:"label"`
	Status    ApiKeyStatus       `json:"status"`
	CreatedAt time.Time          `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Email     string             `json:"email"`
	AccountID uuid.UUID          `json:"account_id"`
	Balance   pgtype.Numeric     `json:"balance"`
	Currency  Currency           `json:"currency"`
}

func (q *Queries) GetKeyWithUserAndAccount(ctx context.Context, keyHash string) (GetKeyWithUserAndAccountRow, error) {
	row := q.db.QueryRow(ctx, getKeyWithUserAndAccount, keyHash)
	var i GetKeyWithUserAndAccountRow
	err := row.Scan(
		&i.ApiKeyID,
		&i.UserID,
		&i.KeyHash,
		&i.Label,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Email,
		&i.AccountID,
		&i.Balance,
		&i.Currency,
	)
	return i, err
}

const insertKey = `-- name: InsertKey :one
INSERT INTO api_keys (user_id, key_hash, label, status, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, key_hash, label, status, created_at, expires_at
`

type InsertKeyParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	KeyHash   string             `json:"key_hash"`
	Label     pgtype.Text        `json:"label"`
	Status    ApiKeyStatus       `json:"status"`
	CreatedAt time.Time          `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertKey(ctx context.Context, arg InsertKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, insertKey,
		arg.UserID,
		arg.KeyHash,
		arg.Label,
		arg.Status,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.Label,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listKeysByUser = `-- name: ListKeysByUser :many
SELECT id, user_id, key_hash, label, status, created_at, expires_at
FROM api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListKeysByUser(ctx context.Context, userID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KeyHash,
			&i.Label,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKeyStatus = `-- name: UpdateKeyStatus :one
UPDATE api_keys
SET status = $2
WHERE id = $1
RETURNING id, user_id, key_hash, label, status, created_at, expires_at
`

type UpdateKeyStatusParams struct {
	ID     uuid.UUID    `json:"id"`
	Status ApiKeyStatus `json:"status"`
}

func (q *Queries) UpdateKeyStatus(ctx context.Context, arg UpdateKeyStatusParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, updateKeyStatus, arg.ID, arg.Status)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.Label,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
