// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deposits.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmDeposit = `-- name: ConfirmDeposit :one
UPDATE deposits
SET status = 'confirmed', confirmed_at = now()
WHERE id = $1
RETURNING id, user_id, from_address, amount, currency, memo, tx_hash, status, created_at, confirmed_at, reason
`

func (q *Queries) ConfirmDeposit(ctx context.Context, id uuid.UUID) (Deposit, error) {
	row := q.db.QueryRow(ctx, confirmDeposit, id)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromAddress,
		&i.Amount,
		&i.Currency,
		&i.Memo,
		&i.TxHash,
		&i.Status,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.Reason,
	)
	return i, err
}

const getDepositByID = `-- name: GetDepositByID :one
SELECT id, user_id, from_address, amount, currency, memo, tx_hash, status, created_at, confirmed_at, reason FROM deposits
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDepositByID(ctx context.Context, id uuid.UUID) (Deposit, error) {
	row := q.db.QueryRow(ctx, getDepositByID, id)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromAddress,
		&i.Amount,
		&i.Currency,
		&i.Memo,
		&i.TxHash,
		&i.Status,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.Reason,
	)
	return i, err
}

const getDepositByTxHash = `-- name: GetDepositByTxHash :one
SELECT id, user_id, from_address, amount, currency, memo, tx_hash, status, created_at, confirmed_at, reason FROM deposits
WHERE tx_hash = $1
LIMIT 1
`

func (q *Queries) GetDepositByTxHash(ctx context.Context, txHash string) (Deposit, error) {
	row := q.db.QueryRow(ctx, getDepositByTxHash, txHash)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromAddress,
		&i.Amount,
		&i.Currency,
		&i.Memo,
		&i.TxHash,
		&i.Status,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.Reason,
	)
	return i, err
}

const insertDeposit = `-- name: InsertDeposit :one
INSERT INTO deposits (
    user_id, from_address, amount, currency, memo, tx_hash, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (tx_hash) DO NOTHING
RETURNING id, user_id, from_address, amount, currency, memo, tx_hash, status, created_at, confirmed_at, reason
`

type InsertDepositParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	FromAddress string         `json:"from_address"`
	Amount      pgtype.Numeric `json:"amount"`
	Currency    Currency       `json:"currency"`
	Memo        pgtype.Text    `json:"memo"`
	TxHash      string         `json:"tx_hash"`
	Status      DepositStatus  `json:"status"`
}

func (q *Queries) InsertDeposit(ctx context.Context, arg InsertDepositParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, insertDeposit,
		arg.UserID,
		arg.FromAddress,
		arg.Amount,
		arg.Currency,
		arg.Memo,
		arg.TxHash,
		arg.Status,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromAddress,
		&i.Amount,
		&i.Currency,
		&i.Memo,
		&i.TxHash,
		&i.Status,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.Reason,
	)
	return i, err
}

const insertDepositIgnoreConflict = `-- name: InsertDepositIgnoreConflict :one
INSERT INTO deposits (
    user_id, from_address, amount, currency, memo, tx_hash, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (tx_hash) DO NOTHING
RETURNING id, user_id, from_address, amount, currency, memo, tx_hash, status, created_at, confirmed_at, reason
`

type InsertDepositIgnoreConflictParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	FromAddress string         `json:"from_address"`
	Amount      pgtype.Numeric `json:"amount"`
	Currency    Currency       `json:"currency"`
	Memo        pgtype.Text    `json:"memo"`
	TxHash      string         `json:"tx_hash"`
	Status      DepositStatus  `json:"status"`
}

func (q *Queries) InsertDepositIgnoreConflict(ctx context.Context, arg InsertDepositIgnoreConflictParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, insertDepositIgnoreConflict,
		arg.UserID,
		arg.FromAddress,
		arg.Amount,
		arg.Currency,
		arg.Memo,
		arg.TxHash,
		arg.Status,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromAddress,
		&i.Amount,
		&i.Currency,
		&i.Memo,
		&i.TxHash,
		&i.Status,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.Reason,
	)
	return i, err
}

const listDepositsByAccount = `-- name: ListDepositsByAccount :many
SELECT id, user_id, from_address, amount, currency, memo, tx_hash, status, created_at, confirmed_at, reason FROM deposits
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDepositsByAccount(ctx context.Context, userID uuid.UUID) ([]Deposit, error) {
	rows, err := q.db.Query(ctx, listDepositsByAccount, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deposit
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FromAddress,
			&i.Amount,
			&i.Currency,
			&i.Memo,
			&i.TxHash,
			&i.Status,
			&i.CreatedAt,
			&i.ConfirmedAt,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDepositRejected = `-- name: MarkDepositRejected :one
UPDATE deposits
SET status = 'failed', reason = $2
WHERE id = $1
RETURNING id, user_id, from_address, amount, currency, memo, tx_hash, status, created_at, confirmed_at, reason
`

type MarkDepositRejectedParams struct {
	ID     uuid.UUID   `json:"id"`
	Reason pgtype.Text `json:"reason"`
}

func (q *Queries) MarkDepositRejected(ctx context.Context, arg MarkDepositRejectedParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, markDepositRejected, arg.ID, arg.Reason)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromAddress,
		&i.Amount,
		&i.Currency,
		&i.Memo,
		&i.TxHash,
		&i.Status,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.Reason,
	)
	return i, err
}

const updateDepositStatus = `-- name: UpdateDepositStatus :one
UPDATE deposits
SET status = $2
WHERE id = $1
RETURNING id, user_id, from_address, amount, currency, memo, tx_hash, status, created_at, confirmed_at, reason
`

type UpdateDepositStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status DepositStatus `json:"status"`
}

func (q *Queries) UpdateDepositStatus(ctx context.Context, arg UpdateDepositStatusParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, updateDepositStatus, arg.ID, arg.Status)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromAddress,
		&i.Amount,
		&i.Currency,
		&i.Memo,
		&i.TxHash,
		&i.Status,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.Reason,
	)
	return i, err
}
