// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deposits_dashboard.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listDepositsByAccountCursor = `-- name: ListDepositsByAccountCursor :many
SELECT id, user_id, from_address, amount, currency, memo, tx_hash, status, created_at, confirmed_at, reason FROM deposits
WHERE user_id = $1
  AND ($3::timestamptz = '0001-01-01'::timestamptz OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListDepositsByAccountCursorParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Limit   int32     `json:"limit"`
	Column3 time.Time `json:"column_3"`
	Column4 uuid.UUID `json:"column_4"`
}

func (q *Queries) ListDepositsByAccountCursor(ctx context.Context, arg ListDepositsByAccountCursorParams) ([]Deposit, error) {
	rows, err := q.db.Query(ctx, listDepositsByAccountCursor,
		arg.UserID,
		arg.Limit,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deposit
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FromAddress,
			&i.Amount,
			&i.Currency,
			&i.Memo,
			&i.TxHash,
			&i.Status,
			&i.CreatedAt,
			&i.ConfirmedAt,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
