// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getAccountBalaance.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT balance
FROM accounts
WHERE owner_id = $1
LIMIT 1
`

func (q *Queries) GetAccountBalance(ctx context.Context, ownerID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getAccountBalance, ownerID)
	var balance pgtype.Numeric
	err := row.Scan(&balance)
	return balance, err
}
