// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getProviderByName.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getProviderByName = `-- name: GetProviderByName :one
SELECT id, base_url, name, owner_id, status, description, created_at, updated_at
FROM providers
WHERE name = $1
  AND "status" = 'active'
LIMIT 1
`

type GetProviderByNameRow struct {
	ID          uuid.UUID      `json:"id"`
	BaseUrl     string         `json:"base_url"`
	Name        string         `json:"name"`
	OwnerID     uuid.UUID      `json:"owner_id"`
	Status      ProviderStatus `json:"status"`
	Description string         `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) GetProviderByName(ctx context.Context, name string) (GetProviderByNameRow, error) {
	row := q.db.QueryRow(ctx, getProviderByName, name)
	var i GetProviderByNameRow
	err := row.Scan(
		&i.ID,
		&i.BaseUrl,
		&i.Name,
		&i.OwnerID,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
