// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getProviderBaseURL.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getProviderBaseURL = `-- name: GetProviderBaseURL :one
SELECT base_url
FROM providers 
WHERE id = $1 
AND "status" = 'active'
LIMIT 1
`

func (q *Queries) GetProviderBaseURL(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getProviderBaseURL, id)
	var base_url string
	err := row.Scan(&base_url)
	return base_url, err
}
