// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger_entries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLedgerEntryByID = `-- name: GetLedgerEntryByID :one
SELECT id, account_id, entry_type, amount, balance_after, currency, reference_id, reference_type, status, description, created_at FROM ledger_entries
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetLedgerEntryByID(ctx context.Context, id uuid.UUID) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, getLedgerEntryByID, id)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.EntryType,
		&i.Amount,
		&i.BalanceAfter,
		&i.Currency,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getLedgerEntryByReferenceID = `-- name: GetLedgerEntryByReferenceID :one
SELECT id, account_id, entry_type, amount, balance_after, currency, reference_id, reference_type, status, description, created_at FROM ledger_entries
WHERE reference_id = $1
LIMIT 1
`

func (q *Queries) GetLedgerEntryByReferenceID(ctx context.Context, referenceID pgtype.UUID) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, getLedgerEntryByReferenceID, referenceID)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.EntryType,
		&i.Amount,
		&i.BalanceAfter,
		&i.Currency,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :one
INSERT INTO ledger_entries (
    account_id, entry_type, amount, balance_after, currency,
    reference_id, reference_type, status, description
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, account_id, entry_type, amount, balance_after, currency, reference_id, reference_type, status, description, created_at
`

type InsertLedgerEntryParams struct {
	AccountID     uuid.UUID      `json:"account_id"`
	EntryType     EntryType      `json:"entry_type"`
	Amount        pgtype.Numeric `json:"amount"`
	BalanceAfter  pgtype.Numeric `json:"balance_after"`
	Currency      Currency       `json:"currency"`
	ReferenceID   pgtype.UUID    `json:"reference_id"`
	ReferenceType pgtype.Text    `json:"reference_type"`
	Status        LedgerStatus   `json:"status"`
	Description   pgtype.Text    `json:"description"`
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.AccountID,
		arg.EntryType,
		arg.Amount,
		arg.BalanceAfter,
		arg.Currency,
		arg.ReferenceID,
		arg.ReferenceType,
		arg.Status,
		arg.Description,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.EntryType,
		&i.Amount,
		&i.BalanceAfter,
		&i.Currency,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerEntriesByAccount = `-- name: ListLedgerEntriesByAccount :many
SELECT id, account_id, entry_type, amount, balance_after, currency, reference_id, reference_type, status, description, created_at FROM ledger_entries
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLedgerEntriesByAccountParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListLedgerEntriesByAccount(ctx context.Context, arg ListLedgerEntriesByAccountParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.EntryType,
			&i.Amount,
			&i.BalanceAfter,
			&i.Currency,
			&i.ReferenceID,
			&i.ReferenceType,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByAccountAndType = `-- name: ListLedgerEntriesByAccountAndType :many
SELECT id, account_id, entry_type, amount, balance_after, currency, reference_id, reference_type, status, description, created_at FROM ledger_entries
WHERE account_id = $1 AND entry_type = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListLedgerEntriesByAccountAndTypeParams struct {
	AccountID uuid.UUID `json:"account_id"`
	EntryType EntryType `json:"entry_type"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListLedgerEntriesByAccountAndType(ctx context.Context, arg ListLedgerEntriesByAccountAndTypeParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByAccountAndType,
		arg.AccountID,
		arg.EntryType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.EntryType,
			&i.Amount,
			&i.BalanceAfter,
			&i.Currency,
			&i.ReferenceID,
			&i.ReferenceType,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLedgerEntryStatus = `-- name: UpdateLedgerEntryStatus :one
UPDATE ledger_entries
SET status = $2
WHERE id = $1
RETURNING id, account_id, entry_type, amount, balance_after, currency, reference_id, reference_type, status, description, created_at
`

type UpdateLedgerEntryStatusParams struct {
	ID     uuid.UUID    `json:"id"`
	Status LedgerStatus `json:"status"`
}

func (q *Queries) UpdateLedgerEntryStatus(ctx context.Context, arg UpdateLedgerEntryStatusParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, updateLedgerEntryStatus, arg.ID, arg.Status)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.EntryType,
		&i.Amount,
		&i.BalanceAfter,
		&i.Currency,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
