// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (owner_id, name, base_url, status)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, name, base_url, status, created_at, updated_at
`

type CreateProviderParams struct {
	OwnerID uuid.UUID      `json:"owner_id"`
	Name    string         `json:"name"`
	BaseUrl string         `json:"base_url"`
	Status  ProviderStatus `json:"status"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.OwnerID,
		arg.Name,
		arg.BaseUrl,
		arg.Status,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :one
DELETE FROM providers
WHERE id = $1
RETURNING id, owner_id, name, base_url, status, created_at, updated_at
`

func (q *Queries) DeleteProvider(ctx context.Context, id uuid.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, deleteProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, owner_id, name, base_url, status, created_at, updated_at
FROM providers
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProviderByID(ctx context.Context, id uuid.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllProviders = `-- name: ListAllProviders :many
SELECT id, owner_id, name, base_url, status, created_at, updated_at
FROM providers
WHERE ($1 IS NULL OR status = $1)
ORDER BY created_at DESC
`

func (q *Queries) ListAllProviders(ctx context.Context, status interface{}) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listAllProviders, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.BaseUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvidersByOwner = `-- name: ListProvidersByOwner :many
SELECT id, owner_id, name, base_url, status, created_at, updated_at
FROM providers
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProvidersByOwner(ctx context.Context, ownerID uuid.UUID) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProvidersByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.BaseUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE providers
SET name = $2,
    base_url = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, owner_id, name, base_url, status, created_at, updated_at
`

type UpdateProviderParams struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	BaseUrl string    `json:"base_url"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProvider, arg.ID, arg.Name, arg.BaseUrl)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProviderStatus = `-- name: UpdateProviderStatus :one
UPDATE providers
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, owner_id, name, base_url, status, created_at, updated_at
`

type UpdateProviderStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status ProviderStatus `json:"status"`
}

func (q *Queries) UpdateProviderStatus(ctx context.Context, arg UpdateProviderStatusParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProviderStatus, arg.ID, arg.Status)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
