// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUsageEvent(ctx context.Context, arg CreateUsageEventParams) (CreateUsageEventRow, error)
	GetAccountBalance(ctx context.Context, ownerID uuid.UUID) (pgtype.Numeric, error)
	GetProviderBaseURL(ctx context.Context, id uuid.UUID) (string, error)
	GetUsageEventByRequestID(ctx context.Context, requestID string) (UsageEvent, error)
	ListUsageEventsByConsumer(ctx context.Context, consumerID uuid.UUID) ([]UsageEvent, error)
}

var _ Querier = (*Queries)(nil)
