// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetProviderBaseURL(ctx context.Context, id uuid.UUID) (string, error)
}

var _ Querier = (*Queries)(nil)
