// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_tokens.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSessionTokenByHash = `-- name: GetSessionTokenByHash :one
SELECT id, user_id, token_hash, label, scope, status, expires_at, created_at
FROM session_tokens
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetSessionTokenByHash(ctx context.Context, tokenHash string) (SessionToken, error) {
	row := q.db.QueryRow(ctx, getSessionTokenByHash, tokenHash)
	var i SessionToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Label,
		&i.Scope,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertSessionToken = `-- name: InsertSessionToken :one
INSERT INTO session_tokens (user_id, token_hash, label, scope, status, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, token_hash, label, scope, status, expires_at, created_at
`

type InsertSessionTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	Label     pgtype.Text        `json:"label"`
	Scope     pgtype.Text        `json:"scope"`
	Status    SessionTokenStatus `json:"status"`
	ExpiresAt time.Time          `json:"expires_at"`
	CreatedAt time.Time          `json:"created_at"`
}

func (q *Queries) InsertSessionToken(ctx context.Context, arg InsertSessionTokenParams) (SessionToken, error) {
	row := q.db.QueryRow(ctx, insertSessionToken,
		arg.UserID,
		arg.TokenHash,
		arg.Label,
		arg.Scope,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i SessionToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Label,
		&i.Scope,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listSessionTokensByUser = `-- name: ListSessionTokensByUser :many
SELECT id, user_id, token_hash, label, scope, status, expires_at, created_at
FROM session_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSessionTokensByUser(ctx context.Context, userID uuid.UUID) ([]SessionToken, error) {
	rows, err := q.db.Query(ctx, listSessionTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionToken
	for rows.Next() {
		var i SessionToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.Label,
			&i.Scope,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionTokenStatus = `-- name: UpdateSessionTokenStatus :one
UPDATE session_tokens
SET status = $2
WHERE id = $1
RETURNING id, user_id, token_hash, label, scope, status, expires_at, created_at
`

type UpdateSessionTokenStatusParams struct {
	ID     uuid.UUID          `json:"id"`
	Status SessionTokenStatus `json:"status"`
}

func (q *Queries) UpdateSessionTokenStatus(ctx context.Context, arg UpdateSessionTokenStatusParams) (SessionToken, error) {
	row := q.db.QueryRow(ctx, updateSessionTokenStatus, arg.ID, arg.Status)
	var i SessionToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Label,
		&i.Scope,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
