// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settlements_dashboard.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listSettlementBatchesByProvider = `-- name: ListSettlementBatchesByProvider :many
SELECT DISTINCT sb.id, sb.status, sb.total_amount, sb.currency, sb.entry_count, sb.tx_hash, sb.created_at, sb.completed_at
FROM settlement_batches sb
JOIN settlement_entries se ON se.batch_id = sb.id
WHERE se.provider_id = $1
  AND ($3::timestamptz = '0001-01-01'::timestamptz OR (sb.created_at, sb.id) < ($3::timestamptz, $4::uuid))
ORDER BY sb.created_at DESC, sb.id DESC
LIMIT $2
`

type ListSettlementBatchesByProviderParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Limit      int32     `json:"limit"`
	Column3    time.Time `json:"column_3"`
	Column4    uuid.UUID `json:"column_4"`
}

func (q *Queries) ListSettlementBatchesByProvider(ctx context.Context, arg ListSettlementBatchesByProviderParams) ([]SettlementBatch, error) {
	rows, err := q.db.Query(ctx, listSettlementBatchesByProvider,
		arg.ProviderID,
		arg.Limit,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SettlementBatch
	for rows.Next() {
		var i SettlementBatch
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.TotalAmount,
			&i.Currency,
			&i.EntryCount,
			&i.TxHash,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
