// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settlements.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSettlementBatchByID = `-- name: GetSettlementBatchByID :one
SELECT id, status, total_amount, currency, entry_count, tx_hash, created_at, completed_at FROM settlement_batches
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSettlementBatchByID(ctx context.Context, id uuid.UUID) (SettlementBatch, error) {
	row := q.db.QueryRow(ctx, getSettlementBatchByID, id)
	var i SettlementBatch
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.TotalAmount,
		&i.Currency,
		&i.EntryCount,
		&i.TxHash,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getSettlementEntryByBatchAndProvider = `-- name: GetSettlementEntryByBatchAndProvider :one
SELECT id, batch_id, provider_id, amount, currency, wallet_address, status, created_at, tx_hash FROM settlement_entries
WHERE batch_id = $1 AND provider_id = $2
LIMIT 1
`

type GetSettlementEntryByBatchAndProviderParams struct {
	BatchID    uuid.UUID `json:"batch_id"`
	ProviderID uuid.UUID `json:"provider_id"`
}

func (q *Queries) GetSettlementEntryByBatchAndProvider(ctx context.Context, arg GetSettlementEntryByBatchAndProviderParams) (SettlementEntry, error) {
	row := q.db.QueryRow(ctx, getSettlementEntryByBatchAndProvider, arg.BatchID, arg.ProviderID)
	var i SettlementEntry
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.ProviderID,
		&i.Amount,
		&i.Currency,
		&i.WalletAddress,
		&i.Status,
		&i.CreatedAt,
		&i.TxHash,
	)
	return i, err
}

const getSettlementEntryByID = `-- name: GetSettlementEntryByID :one
SELECT id, batch_id, provider_id, amount, currency, wallet_address, status, created_at, tx_hash FROM settlement_entries
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSettlementEntryByID(ctx context.Context, id uuid.UUID) (SettlementEntry, error) {
	row := q.db.QueryRow(ctx, getSettlementEntryByID, id)
	var i SettlementEntry
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.ProviderID,
		&i.Amount,
		&i.Currency,
		&i.WalletAddress,
		&i.Status,
		&i.CreatedAt,
		&i.TxHash,
	)
	return i, err
}

const getUnsettledProviderEarnings = `-- name: GetUnsettledProviderEarnings :many
SELECT
    ue.provider_id,
    SUM(ue.request_cost)::numeric AS total_amount,
    ue.currency,
    u.payout_stellar_address
FROM usage_events ue
JOIN providers p ON p.id = ue.provider_id
JOIN users u ON u.id = p.owner_id
WHERE ue.status = 'completed'
  AND u.payout_stellar_address IS NOT NULL
  AND u.payout_stellar_address != ''
  AND ue.created_at > COALESCE((
      SELECT MAX(sb.completed_at)
      FROM settlement_entries se
      JOIN settlement_batches sb ON sb.id = se.batch_id
      WHERE se.provider_id = ue.provider_id
        AND sb.status = 'completed'
  ), 'epoch'::timestamptz)
GROUP BY ue.provider_id, ue.currency, u.payout_stellar_address
`

type GetUnsettledProviderEarningsRow struct {
	ProviderID           uuid.UUID      `json:"provider_id"`
	TotalAmount          pgtype.Numeric `json:"total_amount"`
	Currency             Currency       `json:"currency"`
	PayoutStellarAddress pgtype.Text    `json:"payout_stellar_address"`
}

func (q *Queries) GetUnsettledProviderEarnings(ctx context.Context) ([]GetUnsettledProviderEarningsRow, error) {
	rows, err := q.db.Query(ctx, getUnsettledProviderEarnings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnsettledProviderEarningsRow
	for rows.Next() {
		var i GetUnsettledProviderEarningsRow
		if err := rows.Scan(
			&i.ProviderID,
			&i.TotalAmount,
			&i.Currency,
			&i.PayoutStellarAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSettlementBatch = `-- name: InsertSettlementBatch :one
INSERT INTO settlement_batches (
    status, total_amount, currency, entry_count, tx_hash
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, status, total_amount, currency, entry_count, tx_hash, created_at, completed_at
`

type InsertSettlementBatchParams struct {
	Status      BatchStatus    `json:"status"`
	TotalAmount pgtype.Numeric `json:"total_amount"`
	Currency    Currency       `json:"currency"`
	EntryCount  int32          `json:"entry_count"`
	TxHash      pgtype.Text    `json:"tx_hash"`
}

func (q *Queries) InsertSettlementBatch(ctx context.Context, arg InsertSettlementBatchParams) (SettlementBatch, error) {
	row := q.db.QueryRow(ctx, insertSettlementBatch,
		arg.Status,
		arg.TotalAmount,
		arg.Currency,
		arg.EntryCount,
		arg.TxHash,
	)
	var i SettlementBatch
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.TotalAmount,
		&i.Currency,
		&i.EntryCount,
		&i.TxHash,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertSettlementEntry = `-- name: InsertSettlementEntry :one
INSERT INTO settlement_entries (
    batch_id, provider_id, amount, currency, wallet_address, status
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, batch_id, provider_id, amount, currency, wallet_address, status, created_at, tx_hash
`

type InsertSettlementEntryParams struct {
	BatchID       uuid.UUID             `json:"batch_id"`
	ProviderID    uuid.UUID             `json:"provider_id"`
	Amount        pgtype.Numeric        `json:"amount"`
	Currency      Currency              `json:"currency"`
	WalletAddress string                `json:"wallet_address"`
	Status        SettlementEntryStatus `json:"status"`
}

func (q *Queries) InsertSettlementEntry(ctx context.Context, arg InsertSettlementEntryParams) (SettlementEntry, error) {
	row := q.db.QueryRow(ctx, insertSettlementEntry,
		arg.BatchID,
		arg.ProviderID,
		arg.Amount,
		arg.Currency,
		arg.WalletAddress,
		arg.Status,
	)
	var i SettlementEntry
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.ProviderID,
		&i.Amount,
		&i.Currency,
		&i.WalletAddress,
		&i.Status,
		&i.CreatedAt,
		&i.TxHash,
	)
	return i, err
}

const listFailedSettlementBatches = `-- name: ListFailedSettlementBatches :many
SELECT id, status, total_amount, currency, entry_count, tx_hash, created_at, completed_at FROM settlement_batches
WHERE status = 'failed'
ORDER BY created_at DESC
`

func (q *Queries) ListFailedSettlementBatches(ctx context.Context) ([]SettlementBatch, error) {
	rows, err := q.db.Query(ctx, listFailedSettlementBatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SettlementBatch
	for rows.Next() {
		var i SettlementBatch
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.TotalAmount,
			&i.Currency,
			&i.EntryCount,
			&i.TxHash,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlementBatches = `-- name: ListSettlementBatches :many
SELECT id, status, total_amount, currency, entry_count, tx_hash, created_at, completed_at FROM settlement_batches
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSettlementBatchesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSettlementBatches(ctx context.Context, arg ListSettlementBatchesParams) ([]SettlementBatch, error) {
	rows, err := q.db.Query(ctx, listSettlementBatches, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SettlementBatch
	for rows.Next() {
		var i SettlementBatch
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.TotalAmount,
			&i.Currency,
			&i.EntryCount,
			&i.TxHash,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlementEntriesByBatch = `-- name: ListSettlementEntriesByBatch :many
SELECT id, batch_id, provider_id, amount, currency, wallet_address, status, created_at, tx_hash FROM settlement_entries
WHERE batch_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSettlementEntriesByBatch(ctx context.Context, batchID uuid.UUID) ([]SettlementEntry, error) {
	rows, err := q.db.Query(ctx, listSettlementEntriesByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SettlementEntry
	for rows.Next() {
		var i SettlementEntry
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.ProviderID,
			&i.Amount,
			&i.Currency,
			&i.WalletAddress,
			&i.Status,
			&i.CreatedAt,
			&i.TxHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSettlementBatchStatus = `-- name: UpdateSettlementBatchStatus :one
UPDATE settlement_batches
SET
    status = $2,
    completed_at = CASE
        WHEN $2 IN ('completed', 'failed') THEN COALESCE(completed_at, now())
        WHEN $2 IN ('pending', 'processing') THEN NULL
        ELSE completed_at
    END
WHERE id = $1
RETURNING id, status, total_amount, currency, entry_count, tx_hash, created_at, completed_at
`

type UpdateSettlementBatchStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status BatchStatus `json:"status"`
}

func (q *Queries) UpdateSettlementBatchStatus(ctx context.Context, arg UpdateSettlementBatchStatusParams) (SettlementBatch, error) {
	row := q.db.QueryRow(ctx, updateSettlementBatchStatus, arg.ID, arg.Status)
	var i SettlementBatch
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.TotalAmount,
		&i.Currency,
		&i.EntryCount,
		&i.TxHash,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateSettlementEntryStatus = `-- name: UpdateSettlementEntryStatus :one
UPDATE settlement_entries
SET status = $2
WHERE id = $1
RETURNING id, batch_id, provider_id, amount, currency, wallet_address, status, created_at, tx_hash
`

type UpdateSettlementEntryStatusParams struct {
	ID     uuid.UUID             `json:"id"`
	Status SettlementEntryStatus `json:"status"`
}

func (q *Queries) UpdateSettlementEntryStatus(ctx context.Context, arg UpdateSettlementEntryStatusParams) (SettlementEntry, error) {
	row := q.db.QueryRow(ctx, updateSettlementEntryStatus, arg.ID, arg.Status)
	var i SettlementEntry
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.ProviderID,
		&i.Amount,
		&i.Currency,
		&i.WalletAddress,
		&i.Status,
		&i.CreatedAt,
		&i.TxHash,
	)
	return i, err
}
