// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_event.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUsageEvent = `-- name: CreateUsageEvent :one
WITH inserted AS (
    INSERT INTO usage_events (
        consumer_id,
        provider_id,
        endpoint_id,
        request_cost,
        currency,
        status_code,
        latency_ms,
        response_size,
        request_id,
        status
    ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
    )
    ON CONFLICT (request_id) DO NOTHING
    RETURNING id, consumer_id, provider_id, endpoint_id, request_cost, currency, status_code, latency_ms, response_size, request_id, status, created_at
)
SELECT id, consumer_id, provider_id, endpoint_id, request_cost, currency, status_code, latency_ms, response_size, request_id, status, created_at FROM inserted
UNION ALL
SELECT id, consumer_id, provider_id, endpoint_id, request_cost, currency, status_code, latency_ms, response_size, request_id, status, created_at FROM usage_events
WHERE request_id = $9
  AND NOT EXISTS (SELECT 1 FROM inserted)
`

type CreateUsageEventParams struct {
	ConsumerID   uuid.UUID      `json:"consumer_id"`
	ProviderID   uuid.UUID      `json:"provider_id"`
	EndpointID   uuid.UUID      `json:"endpoint_id"`
	RequestCost  pgtype.Numeric `json:"request_cost"`
	Currency     Currency       `json:"currency"`
	StatusCode   pgtype.Int4    `json:"status_code"`
	LatencyMs    pgtype.Int4    `json:"latency_ms"`
	ResponseSize pgtype.Int4    `json:"response_size"`
	RequestID    string         `json:"request_id"`
	Status       UsageStatus    `json:"status"`
}

type CreateUsageEventRow struct {
	ID           uuid.UUID      `json:"id"`
	ConsumerID   uuid.UUID      `json:"consumer_id"`
	ProviderID   uuid.UUID      `json:"provider_id"`
	EndpointID   uuid.UUID      `json:"endpoint_id"`
	RequestCost  pgtype.Numeric `json:"request_cost"`
	Currency     Currency       `json:"currency"`
	StatusCode   pgtype.Int4    `json:"status_code"`
	LatencyMs    pgtype.Int4    `json:"latency_ms"`
	ResponseSize pgtype.Int4    `json:"response_size"`
	RequestID    string         `json:"request_id"`
	Status       UsageStatus    `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
}

func (q *Queries) CreateUsageEvent(ctx context.Context, arg CreateUsageEventParams) (CreateUsageEventRow, error) {
	row := q.db.QueryRow(ctx, createUsageEvent,
		arg.ConsumerID,
		arg.ProviderID,
		arg.EndpointID,
		arg.RequestCost,
		arg.Currency,
		arg.StatusCode,
		arg.LatencyMs,
		arg.ResponseSize,
		arg.RequestID,
		arg.Status,
	)
	var i CreateUsageEventRow
	err := row.Scan(
		&i.ID,
		&i.ConsumerID,
		&i.ProviderID,
		&i.EndpointID,
		&i.RequestCost,
		&i.Currency,
		&i.StatusCode,
		&i.LatencyMs,
		&i.ResponseSize,
		&i.RequestID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUsageEventByRequestID = `-- name: GetUsageEventByRequestID :one
SELECT id, consumer_id, provider_id, endpoint_id, request_cost, currency, status_code, latency_ms, response_size, request_id, status, created_at FROM usage_events
WHERE request_id = $1
`

func (q *Queries) GetUsageEventByRequestID(ctx context.Context, requestID string) (UsageEvent, error) {
	row := q.db.QueryRow(ctx, getUsageEventByRequestID, requestID)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.ConsumerID,
		&i.ProviderID,
		&i.EndpointID,
		&i.RequestCost,
		&i.Currency,
		&i.StatusCode,
		&i.LatencyMs,
		&i.ResponseSize,
		&i.RequestID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listUsageEventsByConsumer = `-- name: ListUsageEventsByConsumer :many
SELECT id, consumer_id, provider_id, endpoint_id, request_cost, currency, status_code, latency_ms, response_size, request_id, status, created_at FROM usage_events
WHERE consumer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUsageEventsByConsumer(ctx context.Context, consumerID uuid.UUID) ([]UsageEvent, error) {
	rows, err := q.db.Query(ctx, listUsageEventsByConsumer, consumerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageEvent
	for rows.Next() {
		var i UsageEvent
		if err := rows.Scan(
			&i.ID,
			&i.ConsumerID,
			&i.ProviderID,
			&i.EndpointID,
			&i.RequestCost,
			&i.Currency,
			&i.StatusCode,
			&i.LatencyMs,
			&i.ResponseSize,
			&i.RequestID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
