// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_dashboard.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveReservationsSum = `-- name: GetActiveReservationsSum :one
SELECT COALESCE(SUM(amount), 0)::numeric AS total
FROM ledger_entries
WHERE account_id = $1
  AND entry_type = 'reservation'
  AND status = 'pending'
`

func (q *Queries) GetActiveReservationsSum(ctx context.Context, accountID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getActiveReservationsSum, accountID)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const getEarningsByEndpoint = `-- name: GetEarningsByEndpoint :many
SELECT ue.endpoint_id, ep.route, SUM(ue.request_cost)::numeric AS total
FROM usage_events ue
JOIN api_endpoints ep ON ep.id = ue.endpoint_id
WHERE ue.provider_id = $1 AND ue.status = 'completed'
GROUP BY ue.endpoint_id, ep.route
`

type GetEarningsByEndpointRow struct {
	EndpointID uuid.UUID      `json:"endpoint_id"`
	Route      string         `json:"route"`
	Total      pgtype.Numeric `json:"total"`
}

func (q *Queries) GetEarningsByEndpoint(ctx context.Context, providerID uuid.UUID) ([]GetEarningsByEndpointRow, error) {
	rows, err := q.db.Query(ctx, getEarningsByEndpoint, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEarningsByEndpointRow
	for rows.Next() {
		var i GetEarningsByEndpointRow
		if err := rows.Scan(&i.EndpointID, &i.Route, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEarningsByEndpointInRange = `-- name: GetEarningsByEndpointInRange :many
SELECT ue.endpoint_id, ep.route, SUM(ue.request_cost)::numeric AS total
FROM usage_events ue
JOIN api_endpoints ep ON ep.id = ue.endpoint_id
WHERE ue.provider_id = $1 AND ue.status = 'completed'
  AND ($2::timestamptz = '0001-01-01'::timestamptz OR ue.created_at >= $2)
  AND ($3::timestamptz = '0001-01-01'::timestamptz OR ue.created_at <= $3)
GROUP BY ue.endpoint_id, ep.route
`

type GetEarningsByEndpointInRangeParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Column2    time.Time `json:"column_2"`
	Column3    time.Time `json:"column_3"`
}

type GetEarningsByEndpointInRangeRow struct {
	EndpointID uuid.UUID      `json:"endpoint_id"`
	Route      string         `json:"route"`
	Total      pgtype.Numeric `json:"total"`
}

func (q *Queries) GetEarningsByEndpointInRange(ctx context.Context, arg GetEarningsByEndpointInRangeParams) ([]GetEarningsByEndpointInRangeRow, error) {
	rows, err := q.db.Query(ctx, getEarningsByEndpointInRange, arg.ProviderID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEarningsByEndpointInRangeRow
	for rows.Next() {
		var i GetEarningsByEndpointInRangeRow
		if err := rows.Scan(&i.EndpointID, &i.Route, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEarningsSparkline = `-- name: GetEarningsSparkline :many
SELECT DATE(created_at) AS date, SUM(request_cost)::numeric AS amount
FROM usage_events
WHERE provider_id = $1 AND status = 'completed'
  AND created_at >= NOW() - INTERVAL '30 days'
GROUP BY DATE(created_at)
ORDER BY date
`

type GetEarningsSparklineRow struct {
	Date   pgtype.Date    `json:"date"`
	Amount pgtype.Numeric `json:"amount"`
}

func (q *Queries) GetEarningsSparkline(ctx context.Context, providerID uuid.UUID) ([]GetEarningsSparklineRow, error) {
	rows, err := q.db.Query(ctx, getEarningsSparkline, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEarningsSparklineRow
	for rows.Next() {
		var i GetEarningsSparklineRow
		if err := rows.Scan(&i.Date, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEarningsSparklineInRange = `-- name: GetEarningsSparklineInRange :many
SELECT DATE(created_at) AS date, SUM(request_cost)::numeric AS amount
FROM usage_events
WHERE provider_id = $1 AND status = 'completed'
  AND ($2::timestamptz = '0001-01-01'::timestamptz OR created_at >= $2)
  AND ($3::timestamptz = '0001-01-01'::timestamptz OR created_at <= $3)
GROUP BY DATE(created_at)
ORDER BY date
`

type GetEarningsSparklineInRangeParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Column2    time.Time `json:"column_2"`
	Column3    time.Time `json:"column_3"`
}

type GetEarningsSparklineInRangeRow struct {
	Date   pgtype.Date    `json:"date"`
	Amount pgtype.Numeric `json:"amount"`
}

func (q *Queries) GetEarningsSparklineInRange(ctx context.Context, arg GetEarningsSparklineInRangeParams) ([]GetEarningsSparklineInRangeRow, error) {
	rows, err := q.db.Query(ctx, getEarningsSparklineInRange, arg.ProviderID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEarningsSparklineInRangeRow
	for rows.Next() {
		var i GetEarningsSparklineInRangeRow
		if err := rows.Scan(&i.Date, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalEarningsByProvider = `-- name: GetTotalEarningsByProvider :one
SELECT COALESCE(SUM(request_cost), 0)::numeric AS total
FROM usage_events
WHERE provider_id = $1 AND status = 'completed'
`

func (q *Queries) GetTotalEarningsByProvider(ctx context.Context, providerID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalEarningsByProvider, providerID)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const getTotalEarningsByProviderInRange = `-- name: GetTotalEarningsByProviderInRange :one
SELECT COALESCE(SUM(request_cost), 0)::numeric AS total
FROM usage_events
WHERE provider_id = $1 AND status = 'completed'
  AND ($2::timestamptz = '0001-01-01'::timestamptz OR created_at >= $2)
  AND ($3::timestamptz = '0001-01-01'::timestamptz OR created_at <= $3)
`

type GetTotalEarningsByProviderInRangeParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Column2    time.Time `json:"column_2"`
	Column3    time.Time `json:"column_3"`
}

func (q *Queries) GetTotalEarningsByProviderInRange(ctx context.Context, arg GetTotalEarningsByProviderInRangeParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalEarningsByProviderInRange, arg.ProviderID, arg.Column2, arg.Column3)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const getUnsettledEarningsByProvider = `-- name: GetUnsettledEarningsByProvider :one
SELECT COALESCE(SUM(le.amount), 0)::numeric AS total
FROM ledger_entries le
WHERE le.account_id = (SELECT a.id FROM accounts a JOIN providers p ON p.owner_id = a.owner_id WHERE p.id = $1)
  AND le.entry_type = 'settlement'
  AND le.status = 'pending'
`

func (q *Queries) GetUnsettledEarningsByProvider(ctx context.Context, id uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getUnsettledEarningsByProvider, id)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const getUserProviderCount = `-- name: GetUserProviderCount :one
SELECT COUNT(*) AS count
FROM providers
WHERE owner_id = $1
`

func (q *Queries) GetUserProviderCount(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUserProviderCount, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listUsageEventsByConsumerCursor = `-- name: ListUsageEventsByConsumerCursor :many
SELECT ue.id, ue.consumer_id, ue.provider_id, ue.endpoint_id, ue.request_cost, ue.currency, ue.status_code, ue.latency_ms, ue.response_size, ue.request_id, ue.status, ue.created_at, ep.route, ep.method, p.name::text AS provider_name
FROM usage_events ue
JOIN api_endpoints ep ON ep.id = ue.endpoint_id
JOIN providers p ON p.id = ue.provider_id
WHERE ue.consumer_id = $1
  AND ($3::timestamptz = '0001-01-01'::timestamptz OR (ue.created_at, ue.id) < ($3::timestamptz, $4::uuid))
ORDER BY ue.created_at DESC, ue.id DESC
LIMIT $2
`

type ListUsageEventsByConsumerCursorParams struct {
	ConsumerID uuid.UUID `json:"consumer_id"`
	Limit      int32     `json:"limit"`
	Column3    time.Time `json:"column_3"`
	Column4    uuid.UUID `json:"column_4"`
}

type ListUsageEventsByConsumerCursorRow struct {
	ID           uuid.UUID      `json:"id"`
	ConsumerID   uuid.UUID      `json:"consumer_id"`
	ProviderID   uuid.UUID      `json:"provider_id"`
	EndpointID   uuid.UUID      `json:"endpoint_id"`
	RequestCost  pgtype.Numeric `json:"request_cost"`
	Currency     Currency       `json:"currency"`
	StatusCode   pgtype.Int4    `json:"status_code"`
	LatencyMs    pgtype.Int4    `json:"latency_ms"`
	ResponseSize pgtype.Int4    `json:"response_size"`
	RequestID    string         `json:"request_id"`
	Status       UsageStatus    `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	Route        string         `json:"route"`
	Method       string         `json:"method"`
	ProviderName string         `json:"provider_name"`
}

func (q *Queries) ListUsageEventsByConsumerCursor(ctx context.Context, arg ListUsageEventsByConsumerCursorParams) ([]ListUsageEventsByConsumerCursorRow, error) {
	rows, err := q.db.Query(ctx, listUsageEventsByConsumerCursor,
		arg.ConsumerID,
		arg.Limit,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsageEventsByConsumerCursorRow
	for rows.Next() {
		var i ListUsageEventsByConsumerCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.ConsumerID,
			&i.ProviderID,
			&i.EndpointID,
			&i.RequestCost,
			&i.Currency,
			&i.StatusCode,
			&i.LatencyMs,
			&i.ResponseSize,
			&i.RequestID,
			&i.Status,
			&i.CreatedAt,
			&i.Route,
			&i.Method,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageEventsByConsumerFiltered = `-- name: ListUsageEventsByConsumerFiltered :many
SELECT ue.id, ue.consumer_id, ue.provider_id, ue.endpoint_id, ue.request_cost, ue.currency, ue.status_code, ue.latency_ms, ue.response_size, ue.request_id, ue.status, ue.created_at, ep.route, ep.method, p.name::text AS provider_name
FROM usage_events ue
JOIN api_endpoints ep ON ep.id = ue.endpoint_id
JOIN providers p ON p.id = ue.provider_id
WHERE ue.consumer_id = $1
  AND ($9::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR ue.provider_id = $9)
  AND ($2::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR ue.endpoint_id = $2)
  AND ($3 = 0 OR ue.status_code = $3)
  AND ($4::timestamptz = '0001-01-01'::timestamptz OR ue.created_at >= $4)
  AND ($5::timestamptz = '0001-01-01'::timestamptz OR ue.created_at <= $5)
  AND ($7::timestamptz = '0001-01-01'::timestamptz OR (ue.created_at, ue.id) < ($7::timestamptz, $8::uuid))
ORDER BY ue.created_at DESC, ue.id DESC
LIMIT $6
`

type ListUsageEventsByConsumerFilteredParams struct {
	ConsumerID uuid.UUID   `json:"consumer_id"`
	Column2    uuid.UUID   `json:"column_2"`
	Column3    interface{} `json:"column_3"`
	Column4    time.Time   `json:"column_4"`
	Column5    time.Time   `json:"column_5"`
	Limit      int32       `json:"limit"`
	Column7    time.Time   `json:"column_7"`
	Column8    uuid.UUID   `json:"column_8"`
	Column9    uuid.UUID   `json:"column_9"`
}

type ListUsageEventsByConsumerFilteredRow struct {
	ID           uuid.UUID      `json:"id"`
	ConsumerID   uuid.UUID      `json:"consumer_id"`
	ProviderID   uuid.UUID      `json:"provider_id"`
	EndpointID   uuid.UUID      `json:"endpoint_id"`
	RequestCost  pgtype.Numeric `json:"request_cost"`
	Currency     Currency       `json:"currency"`
	StatusCode   pgtype.Int4    `json:"status_code"`
	LatencyMs    pgtype.Int4    `json:"latency_ms"`
	ResponseSize pgtype.Int4    `json:"response_size"`
	RequestID    string         `json:"request_id"`
	Status       UsageStatus    `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	Route        string         `json:"route"`
	Method       string         `json:"method"`
	ProviderName string         `json:"provider_name"`
}

func (q *Queries) ListUsageEventsByConsumerFiltered(ctx context.Context, arg ListUsageEventsByConsumerFilteredParams) ([]ListUsageEventsByConsumerFilteredRow, error) {
	rows, err := q.db.Query(ctx, listUsageEventsByConsumerFiltered,
		arg.ConsumerID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Column7,
		arg.Column8,
		arg.Column9,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsageEventsByConsumerFilteredRow
	for rows.Next() {
		var i ListUsageEventsByConsumerFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.ConsumerID,
			&i.ProviderID,
			&i.EndpointID,
			&i.RequestCost,
			&i.Currency,
			&i.StatusCode,
			&i.LatencyMs,
			&i.ResponseSize,
			&i.RequestID,
			&i.Status,
			&i.CreatedAt,
			&i.Route,
			&i.Method,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageEventsByProviderCursor = `-- name: ListUsageEventsByProviderCursor :many
SELECT ue.id, ue.consumer_id, ue.provider_id, ue.endpoint_id, ue.request_cost, ue.currency, ue.status_code, ue.latency_ms, ue.response_size, ue.request_id, ue.status, ue.created_at, ep.route, ep.method, p.name::text AS provider_name
FROM usage_events ue
JOIN api_endpoints ep ON ep.id = ue.endpoint_id
JOIN providers p ON p.id = ue.provider_id
WHERE ue.provider_id = $1
  AND ($3::timestamptz = '0001-01-01'::timestamptz OR (ue.created_at, ue.id) < ($3::timestamptz, $4::uuid))
ORDER BY ue.created_at DESC, ue.id DESC
LIMIT $2
`

type ListUsageEventsByProviderCursorParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Limit      int32     `json:"limit"`
	Column3    time.Time `json:"column_3"`
	Column4    uuid.UUID `json:"column_4"`
}

type ListUsageEventsByProviderCursorRow struct {
	ID           uuid.UUID      `json:"id"`
	ConsumerID   uuid.UUID      `json:"consumer_id"`
	ProviderID   uuid.UUID      `json:"provider_id"`
	EndpointID   uuid.UUID      `json:"endpoint_id"`
	RequestCost  pgtype.Numeric `json:"request_cost"`
	Currency     Currency       `json:"currency"`
	StatusCode   pgtype.Int4    `json:"status_code"`
	LatencyMs    pgtype.Int4    `json:"latency_ms"`
	ResponseSize pgtype.Int4    `json:"response_size"`
	RequestID    string         `json:"request_id"`
	Status       UsageStatus    `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	Route        string         `json:"route"`
	Method       string         `json:"method"`
	ProviderName string         `json:"provider_name"`
}

func (q *Queries) ListUsageEventsByProviderCursor(ctx context.Context, arg ListUsageEventsByProviderCursorParams) ([]ListUsageEventsByProviderCursorRow, error) {
	rows, err := q.db.Query(ctx, listUsageEventsByProviderCursor,
		arg.ProviderID,
		arg.Limit,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsageEventsByProviderCursorRow
	for rows.Next() {
		var i ListUsageEventsByProviderCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.ConsumerID,
			&i.ProviderID,
			&i.EndpointID,
			&i.RequestCost,
			&i.Currency,
			&i.StatusCode,
			&i.LatencyMs,
			&i.ResponseSize,
			&i.RequestID,
			&i.Status,
			&i.CreatedAt,
			&i.Route,
			&i.Method,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageEventsByProviderFiltered = `-- name: ListUsageEventsByProviderFiltered :many
SELECT ue.id, ue.consumer_id, ue.provider_id, ue.endpoint_id, ue.request_cost, ue.currency, ue.status_code, ue.latency_ms, ue.response_size, ue.request_id, ue.status, ue.created_at, ep.route, ep.method, p.name::text AS provider_name
FROM usage_events ue
JOIN api_endpoints ep ON ep.id = ue.endpoint_id
JOIN providers p ON p.id = ue.provider_id
WHERE ue.provider_id = $1
  AND ($2::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR ue.endpoint_id = $2)
  AND ($3 = 0 OR ue.status_code = $3)
  AND ($4::timestamptz = '0001-01-01'::timestamptz OR ue.created_at >= $4)
  AND ($5::timestamptz = '0001-01-01'::timestamptz OR ue.created_at <= $5)
  AND ($7::timestamptz = '0001-01-01'::timestamptz OR (ue.created_at, ue.id) < ($7::timestamptz, $8::uuid))
ORDER BY ue.created_at DESC, ue.id DESC
LIMIT $6
`

type ListUsageEventsByProviderFilteredParams struct {
	ProviderID uuid.UUID   `json:"provider_id"`
	Column2    uuid.UUID   `json:"column_2"`
	Column3    interface{} `json:"column_3"`
	Column4    time.Time   `json:"column_4"`
	Column5    time.Time   `json:"column_5"`
	Limit      int32       `json:"limit"`
	Column7    time.Time   `json:"column_7"`
	Column8    uuid.UUID   `json:"column_8"`
}

type ListUsageEventsByProviderFilteredRow struct {
	ID           uuid.UUID      `json:"id"`
	ConsumerID   uuid.UUID      `json:"consumer_id"`
	ProviderID   uuid.UUID      `json:"provider_id"`
	EndpointID   uuid.UUID      `json:"endpoint_id"`
	RequestCost  pgtype.Numeric `json:"request_cost"`
	Currency     Currency       `json:"currency"`
	StatusCode   pgtype.Int4    `json:"status_code"`
	LatencyMs    pgtype.Int4    `json:"latency_ms"`
	ResponseSize pgtype.Int4    `json:"response_size"`
	RequestID    string         `json:"request_id"`
	Status       UsageStatus    `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	Route        string         `json:"route"`
	Method       string         `json:"method"`
	ProviderName string         `json:"provider_name"`
}

func (q *Queries) ListUsageEventsByProviderFiltered(ctx context.Context, arg ListUsageEventsByProviderFilteredParams) ([]ListUsageEventsByProviderFilteredRow, error) {
	rows, err := q.db.Query(ctx, listUsageEventsByProviderFiltered,
		arg.ProviderID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Column7,
		arg.Column8,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsageEventsByProviderFilteredRow
	for rows.Next() {
		var i ListUsageEventsByProviderFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.ConsumerID,
			&i.ProviderID,
			&i.EndpointID,
			&i.RequestCost,
			&i.Currency,
			&i.StatusCode,
			&i.LatencyMs,
			&i.ResponseSize,
			&i.RequestID,
			&i.Status,
			&i.CreatedAt,
			&i.Route,
			&i.Method,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
