// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const ensureUserDepositMemo = `-- name: EnsureUserDepositMemo :one
UPDATE users
SET deposit_memo = COALESCE(deposit_memo, gen_random_uuid()::text)
WHERE id = $1
RETURNING deposit_memo
`

func (q *Queries) EnsureUserDepositMemo(ctx context.Context, id uuid.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, ensureUserDepositMemo, id)
	var deposit_memo pgtype.Text
	err := row.Scan(&deposit_memo)
	return deposit_memo, err
}

const getUserByDepositMemo = `-- name: GetUserByDepositMemo :one
SELECT id, email, deposit_memo, payout_stellar_address, created_at, updated_at FROM users
WHERE deposit_memo = $1
LIMIT 1
`

func (q *Queries) GetUserByDepositMemo(ctx context.Context, depositMemo pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDepositMemo, depositMemo)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DepositMemo,
		&i.PayoutStellarAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
