// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const ensureUserDepositMemo = `-- name: EnsureUserDepositMemo :one
UPDATE users
SET deposit_memo = COALESCE(deposit_memo, $2::VARCHAR(26))
WHERE id = $1
RETURNING deposit_memo
`

type EnsureUserDepositMemoParams struct {
	ID      uuid.UUID `json:"id"`
	NewMemo string    `json:"new_memo"`
}

func (q *Queries) EnsureUserDepositMemo(ctx context.Context, arg EnsureUserDepositMemoParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, ensureUserDepositMemo, arg.ID, arg.NewMemo)
	var deposit_memo pgtype.Text
	err := row.Scan(&deposit_memo)
	return deposit_memo, err
}

const getUserByDepositMemo = `-- name: GetUserByDepositMemo :one
SELECT id, email, deposit_memo, payout_stellar_address, created_at, updated_at, balance, currency, account_updated_at FROM users
WHERE deposit_memo = $1
LIMIT 1
`

func (q *Queries) GetUserByDepositMemo(ctx context.Context, depositMemo pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDepositMemo, depositMemo)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DepositMemo,
		&i.PayoutStellarAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Balance,
		&i.Currency,
		&i.AccountUpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, deposit_memo, payout_stellar_address, created_at, updated_at, balance, currency, account_updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DepositMemo,
		&i.PayoutStellarAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Balance,
		&i.Currency,
		&i.AccountUpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, deposit_memo, payout_stellar_address, created_at, updated_at, balance, currency, account_updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DepositMemo,
		&i.PayoutStellarAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Balance,
		&i.Currency,
		&i.AccountUpdatedAt,
	)
	return i, err
}

const setUserPayoutAddress = `-- name: SetUserPayoutAddress :one
UPDATE users SET payout_stellar_address = $2, updated_at = NOW() WHERE id = $1 RETURNING id, email, deposit_memo, payout_stellar_address, created_at, updated_at, balance, currency, account_updated_at
`

type SetUserPayoutAddressParams struct {
	ID                   uuid.UUID   `json:"id"`
	PayoutStellarAddress pgtype.Text `json:"payout_stellar_address"`
}

func (q *Queries) SetUserPayoutAddress(ctx context.Context, arg SetUserPayoutAddressParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserPayoutAddress, arg.ID, arg.PayoutStellarAddress)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DepositMemo,
		&i.PayoutStellarAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Balance,
		&i.Currency,
		&i.AccountUpdatedAt,
	)
	return i, err
}

const upsertUserByEmail = `-- name: UpsertUserByEmail :one
INSERT INTO users (email)
VALUES ($1)
ON CONFLICT (email) DO UPDATE
  SET updated_at = NOW()
RETURNING id, email, deposit_memo, payout_stellar_address, created_at, updated_at, balance, currency, account_updated_at, (created_at = updated_at) AS is_new
`

type UpsertUserByEmailRow struct {
	ID                   uuid.UUID      `json:"id"`
	Email                string         `json:"email"`
	DepositMemo          pgtype.Text    `json:"deposit_memo"`
	PayoutStellarAddress pgtype.Text    `json:"payout_stellar_address"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	Balance              pgtype.Numeric `json:"balance"`
	Currency             Currency       `json:"currency"`
	AccountUpdatedAt     time.Time      `json:"account_updated_at"`
	IsNew                bool           `json:"is_new"`
}

func (q *Queries) UpsertUserByEmail(ctx context.Context, email string) (UpsertUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, upsertUserByEmail, email)
	var i UpsertUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DepositMemo,
		&i.PayoutStellarAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Balance,
		&i.Currency,
		&i.AccountUpdatedAt,
		&i.IsNew,
	)
	return i, err
}
