// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watcher_cursor.sql

package repository

import (
	"context"
)

const getWatcherCursor = `-- name: GetWatcherCursor :one
SELECT id, cursor, updated_at FROM stellar_watcher_cursor
WHERE id = 1
LIMIT 1
`

func (q *Queries) GetWatcherCursor(ctx context.Context) (StellarWatcherCursor, error) {
	row := q.db.QueryRow(ctx, getWatcherCursor)
	var i StellarWatcherCursor
	err := row.Scan(&i.ID, &i.Cursor, &i.UpdatedAt)
	return i, err
}

const upsertWatcherCursor = `-- name: UpsertWatcherCursor :exec
INSERT INTO stellar_watcher_cursor (id, cursor, updated_at)
VALUES (1, $1, now())
ON CONFLICT (id)
DO UPDATE SET cursor = EXCLUDED.cursor, updated_at = now()
`

func (q *Queries) UpsertWatcherCursor(ctx context.Context, cursor string) error {
	_, err := q.db.Exec(ctx, upsertWatcherCursor, cursor)
	return err
}
